### ISSUE TITLE
Problème avec le volume

### ISSUE THREAD

**Issue by pawel956** [alexandregv/onset-server#1]
Bonjour,

Je n'arrive pas à sauvegarder les données lorsque j'exécute cette commande : 
`docker run -d -p 7777:7777 -p 7776:7776 -p 7775:7775 alexandregv/onset-server -v onset_data:/Steam/OnsetServer`, mais le serveur démarre bien !

De plus il y a une faute sur le site docker hub dans basic usage, la commande pour lancer le conteneur, docker run -d -p 7777:7777 -p 7776:7776 -p 7775:7775 **alexandreg**/onset-server alors que c'est **alexandregv**

Merci d'avance.

**Comment by alexandregv** [comment]
Hey, merci du retour !

Je suis en train d'update ce repo pour ajouter un docker-compose qui facilitera l'utilisation des volumes (et l'utilisation globale).
En fait en ce qui concerne la sauvegarde des données, Onset ne save rien de lui même par défaut.
Je t'avoue que j'ai fait ce Dockerfile rapidement et j'avais à peine commencé à dev sur le jeu, j'avais pas fait gaffe à ce *petit* détail ^^

Pour la deuxième remarque, en effet petite typo, je fixe ça de suite :slightly_smiling_face:

**Comment by pawel956** [comment]
Ah ça me rassure, parce que comme je viens d'apprendre à utiliser docker et docker compose je pensais que ça venait de moi ...

Merci !
J'attends ton update 😃

**Comment by alexandregv** [comment]
Je crois pas encore avoir vu de package pour auto save un world toutes les X minutes par exemple, par contre si tu souhaites faire des modifications dans ton world et les sauvegarder, je te conseille ces deux packages du meme auteur: 
- [sandbox-editor](https://github.com/dig/onset-sandbox-editor): permet d'ajouter/déplacer/supprimer des objets, vehicules, PNJ, etc
- [world](https://github.com/dig/onset-world): permet de charger un world créé avec [sandbox-editor](https://github.com/dig/onset-sandbox-editor)

Je vais vérifier si aucun package de save n'existe, et si c'est bien le cas alors je vais le créer moi même et le publier :wink:

**Comment by pawel956** [comment]
D'accord, merci pour les suggestions, mais je t'avoue que je m'y suis pas trop encore penché sur la partie dév^^.
