### ISSUE TITLE
Problème lors de l'initialisation du conteneur

### ISSUE THREAD

**Issue by pawel956** [alexandregv/onset-server#2]
Bonjour,

Après avoir recopier le fichier docker-compose, quand j'exécute cette commande `docker-compose build && docker-compose up -d`, j'ai cette erreur :

`ERROR: for projetonset_server_1  Cannot start service server: OCI runtime create failed: container_linux.go:346: starting container process caused "process_linux.go:449: container init caused \"rootfs_linux.go:58: mounting \\\"/root/projetonset/server_config.json\\\" to rootfs \\\"/var/lib/docker/overlay2/3176b26e44019985b91c9d9597f5f1df1b76dbba8883bc088f744b752c810675/merged\\\" at \\\"/var/lib/docker/overlay2/3176b26e44019985b91c9d9597f5f1df1b76dbba8883bc088f744b752c810675/merged/Steam/OnsetServer/server_config.json\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type`

`ERROR: for server  Cannot start service server: OCI runtime create failed: container_linux.go:346: starting container process caused "process_linux.go:449: container init caused \"rootfs_linux.go:58: mounting \\\"/root/projetonset/server_config.json\\\" to rootfs \\\"/var/lib/docker/overlay2/3176b26e44019985b91c9d9597f5f1df1b76dbba8883bc088f744b752c810675/merged\\\" at \\\"/var/lib/docker/overlay2/3176b26e44019985b91c9d9597f5f1df1b76dbba8883bc088f744b752c810675/merged/Steam/OnsetServer/server_config.json\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
ERROR: Encountered errors while bringing up the project.`

Et quand j'exécute `ls -l`, je vois qu'il a créer deux dossiers : 
- packages (qui est vide) 
- serveur_config.json (qui est un dossier !)

Donc il n'arrive pas à récupérer les fichiers du conteneur docker et à les mettre sur la machine.

Et il manque `apt-get install libmariadbclient-dev` dans le Dockerfile pour pouvoir connecter le serveur onset à une base de données

Merci d'avance.
Désolé de vous déranger encore ...

**Comment by alexandregv** [comment]
Bonjour,

- Le dossier `packages` est vide car tu n'en as pas sur ton host (et ce n'est pas grave, docker-compose le crée).
- Il crée un dosier `server_config.json` car tu ne fournis pas de fichier [server_config.json](https://dev.playonset.com/wiki/server_config). C'est le comportement de docker-compose: s'il ne trouve pas un volume, il crée un dossier. Je vais ajouter une mention dans le README pour clarifier ça.
- Je vais effectivement ajouter `libmariadbclient-dev`.
